### ISSUE TITLE
Map error in one to one relation with simple derived identity in cascade

### ISSUE THREAD

**Issue by j2perez** [doctrine/DoctrineORMModule#289]
I have the following four entities defined in yaml:

```
EntityA:
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToOne:
        entityB:
            targetEntity: EntityB
            mappedBy: entityA

EntityB:
    id:
        entityA:
            associationKey: true
            column: entityA_id
    oneToOne:
        entityA:
            targetEntity: EntityA
            inversedBy: entityB
        entityC:
            targetEntity: EntityC
            mappedBy: entityB

EntityC
    id:
        entityB:
            associationKey: true
            column: entityB_id
    oneToOne:
        entityB:
            targetEntity: EntityB
            inversedBy: entityC
            joinColumn:
                name: entityB_id
                referencedColumnName: entityA_id

EntityD:
    id:
        entityA:
            associationKey: true
            column: entityA_id
    oneToOne:
        entityA:
            targetEntity: EntityA
```

As you can see i'm using simple derived identity in cascade (EntityA->EntityB->EntityC and EntityA->EntityD) following the documentation instructions (http://docs.doctrine-project.org/en/latest/tutorials/composite-primary-keys.html#use-case-2-simple-derived-identity) . In most cases everything works fine, but in EntityD when i try to execute $this->getEntityA()->getEntityB() i get "The column entityA_id must be mapped to a field in class EntityB since it is referenced by a join column of another class." The another class it's referring is EntityC, but i don't understand why.  EntityB has column entityA_id defined as id, but apparently "referencedColumnName" in EntityC doesn't recognize this (if i redefine entityA_id in other field of EntityB, the error disappear, but then i get a duplicated column).
